import { Link, useNavigate } from 'react-router-dom';
import { useEffect, useState } from 'react';
import { ArrowDownToLine, ArrowUpRight, Check, Copy, Eye, Plus, Trash2, X } from 'lucide-react';
import AssetVisual from '@/components/AssetVisual';
import { getDownloads, subscribeDownloads, removeDownload } from '@/data/downloads';
export default function AssetCard({asset,index,onAdd,onDownload,onDuplicate,selected,busy}){
  const [hover,setHover]=useState(false),[position,setPosition]=useState({x:0,y:0}),[resolution,setResolution]=useState('LOADING'),[preview,setPreview]=useState(false);
  const [downloads,setDownloads]=useState(getDownloads());
  useEffect(()=>subscribeDownloads(()=>setDownloads(getDownloads())),[]);
  useEffect(()=>{if(asset.type!=='image')return;const image=new window.Image();image.onload=()=>setResolution(`${image.naturalWidth} × ${image.naturalHeight}`);image.src=asset.image},[asset]);
  const navigate=useNavigate();
  const url=typeof window!=='undefined'?`${window.location.origin}/embed/${asset.slug}`:'';
  const downloaded=downloads.includes(asset.slug);
  return <article className="asset-card" data-slug={asset.slug} id={asset.slug} onMouseEnter={()=>setHover(true)} onMouseLeave={()=>setHover(false)} onMouseMove={e=>{const r=e.currentTarget.getBoundingClientRect();setPosition({x:Math.round(e.clientX-r.left),y:Math.round(e.clientY-r.top)})}}>
  <div className="asset-visual" onClick={()=>navigate(`/asset/${asset.slug}`)} role="button" tabIndex={0} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();navigate(`/asset/${asset.slug}`)}}}><AssetVisual asset={asset} className="asset-media"/><div className="asset-vignette"/>{hover&&<div className="scanline" style={{top:position.y}}/>}{downloaded&&<div className="asset-downloaded"><Check size={13}/> DOWNLOADED</div>}{asset.forked&&<div className="asset-forktag">FORK{asset.forkOf?` / ${asset.forkOf}`:''}</div>}<div className="asset-topline"><span>SV / {String(index+1).padStart(3,'0')}</span><span>{asset.type==='video'?'MOTION LOOP / WEBM EXPORT':'STATIC / IMAGE'}</span></div><div className="asset-center"><span className="eyebrow">{asset.family}</span><h2>{asset.title}</h2><p>{asset.description}</p>{asset.postedBy&&<span className="asset-posted">POSTED BY {asset.postedBy}</span>}</div><div className="asset-overlay"><span>EMBED // &lt;iframe src="{url}"&gt;&lt;/iframe&gt;</span><span>{asset.type==='image'?`FETCH // curl -L "${asset.image}" -o ${asset.slug}.jpg`:'EXPORT // /get '+asset.slug}</span></div><div className="asset-coords">{hover?`X:${position.x} Y:${position.y} / ${asset.color.toUpperCase()}`:`CHROMA ${asset.color.toUpperCase()}`}</div></div>
  <div className="asset-actions"><div className="asset-identity"><span className="eyebrow">{asset.type==='video'?'MOVING IMAGE':'DIGITAL STILL'} <span className="muted">/</span> {asset.duration||resolution} / {asset.type==='video'?'30 FPS':'8-BIT / CHANNEL'}</span><strong>{asset.slug}</strong></div><div className="action-group"><button onClick={()=>onAdd(asset)} className={selected?'mini-action selected':'mini-action'} aria-label={`${selected?'Remove':'Add'} ${asset.title} ${selected?'from':'to'} download queue`}><Plus size={17}/><span>{selected?'QUEUED':'ADD'}</span></button>
<button onClick={()=>setPreview(true)} className="mini-action" aria-label={`Preview ${asset.title}`}><Eye size={17}/><span>PREVIEW</span></button><button onClick={()=>onDownload(asset)} disabled={busy} className="mini-action" aria-label={`Download ${asset.title}`}><ArrowDownToLine size={17}/><span>{busy?'WORKING':downloaded?'GET AGAIN':'GET'}</span></button>{downloaded&&onDuplicate&&<button onClick={()=>onDuplicate(asset)} disabled={busy} className="mini-action" aria-label={`Duplicate ${asset.title}`}><Copy size={16}/><span>DUPE</span></button>}{downloaded&&<button onClick={()=>removeDownload(asset.slug)} className="mini-action" aria-label={`Remove download ${asset.title}`}><Trash2 size={16}/><span>DEL</span></button>}<Link to={`/asset/${asset.slug}`} className="detail-action">EXPLORE <ArrowUpRight size={19}/></Link></div></div>
  {preview&&<div className="asset-lightbox" onClick={()=>setPreview(false)} role="dialog" aria-modal="true"><button className="lightbox-close" onClick={()=>setPreview(false)} aria-label="Close preview"><X size={22}/></button><div className="lightbox-frame" onClick={e=>e.stopPropagation()}>{asset.type==='image'?<img src={asset.image} alt={asset.title} className="lightbox-media"/>:<AssetVisual asset={asset} className="lightbox-media"/>}</div></div>}
  </article>;
}